In [1]:
import numpy as np

In [17]:
# print all array in one line
np.set_printoptions(linewidth=1000)

In [24]:
# explicit euler method for heat equation

# parameters
L = 1.0
Nx = 10
Nt = 100
kappa = 1.0
dx = L / Nx
dt = 0.01/2+0.001
lamb = kappa * dt / dx**2
print(lamb)

# initial condition
u = np.zeros(Nx)
# change only the middle point to 1
u[Nx//2] = 1.0
print(u)

U = np.zeros((Nt, Nx))
U[0] = u
# time stepping
for n in range(Nt):
    unew = np.zeros(Nx-2)
    unew = (1 - 2*lamb) * u[1:-1] + lamb * (u[:-2] + u[2:])
    u[1:-1] = unew
    U[n] = u
print(U)

0.5999999999999999
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00  6.00000000e-01 -2.00000000e-01  6.00000000e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.60000000e-01 -2.40000000e-01  7.60000000e-01 -2.40000000e-01  3.60000000e-01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.16000000e-01 -2.16000000e-01  7.20000000e-01 -4.40000000e-01  7.20000000e-01 -2.16000000e-01  2.16000000e-01  0.00000000e+00]
 [ 0.00000000e+00  1.29600000e-01 -1.72800000e-01  6.04800000e-01 -5.37600000e-01  9.52000000e-01 -5.37600000e-01  6.04800000e-01 -1.72800000e-01  0.00000000e+00]
 [ 0.00000000e+00 -1.29600000e-01  4.75200000e-01 -5.47200000e-01  1.04160000e+00 -8.35520000e-01  1.04160000e+00 -5.47200000e-01  3.97440000e-01  0.00000000e+00]
 [ 0.00000000e+00  3.11040000e-01 -5.01120000e-01  1.01952000e+00 -1.03795200e+00  1.41702400e+00 -1.03795200e+00  9.72864000e-01 -4.0

In [15]:
lamb

0.9999999999999998